services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - '--log.level=INFO'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.acmeresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.acmeresolver.acme.email=khutwah-production@rockybars.com'
      - '--certificatesresolvers.acmeresolver.acme.storage=/letsencrypt/acme.json'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  letsencrypt:

