name: deploy-mh

on:
  push:
    branches:
      - main
    paths:
      - 'mh/**'

  workflow_dispatch:
    inputs:
      production:
        type: string
      staging:
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: './.github/reusables/deploy-web.yaml'
    secrets: inherit
    with:
      namespace: mh
      staging: ${{ inputs.staging }}
      production: ${{ inputs.production }}
